---
- name: Setup Kubernetes on PCs
  hosts: all
  become: true
  become_user: root
  become_method: sudo

  tasks:
    - name: Update package cache
      apt:
        update_cache: yes

    - name: Install required packages for Kubernetes
      apt:
        name:
          - apt-transport-https
          - curl
        state: present

    - name: Create containerd directory
      file:
        path: /etc/containerd
        state: directory

    - name: Configure containerd
      command: >
        sudo sh -c "containerd config default > /etc/containerd/config.toml"
      args:
        creates: /etc/containerd/config.toml

    - name: Enable SystemdCgroup in containerd config
      replace:
        path: /etc/containerd/config.toml
        regexp: '^(SystemdCgroup\s*=\s*)false'
        replace: '\1true'

    - name: Restart containerd
      systemd:
        name: containerd
        state: restarted

    - name: Add Kubernetes GPG key
      shell: curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add
      args:
        warn: false

    - name: Add Kubernetes repository
      apt_repository:
        repo: "deb http://apt.kubernetes.io/ kubernetes-xenial main"
        state: present

    - name: Install Kubernetes components
      apt:
        name:
          - kubeadm
          - kubelet
          - kubectl
          - kubernetes-cni
        state: present

    - name: Disable swap
      command: swapoff -a

    - name: Load kernel module
      command: modprobe br_netfilter

    - name: Enable IP forwarding
      sysctl:
        name: net.ipv4.ip_forward
        value: 1
        state: present
        reload: yes

  vars_prompt:
    - name: "ansible_become_pass"
      prompt: "Enter sudo password"
      private: yes
